apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-auth-service
  template:
    metadata:
      labels:
        app: lissa-trading-auth-service
    spec:
      containers:
        - name: auth-service
          image: belaquaaa/lissa-trading-auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/lissa-trading-db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root-password-123
            - name: SPRING_DATA_DEFAULT_SCHEMA
              value: auth_service_db
            - name: JWT_SECRET
              value: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb
            - name: JWT_EXPIRATION
              value: "86400000"
            - name: JWT_REFRESH_EXPIRATION
              value: "86400000"
            - name: CACHE_EXPIRE_AFTER_WRITE
              value: "5"
            - name: CACHE_MAXIMUM_SIZE
              value: "100"
            - name: AUTH_SERVICE_URL
              value: http://lissa-trading-auth-service:8081
            - name: USER_SERVICE_URL
              value: http://lissa-trading-user-service:8080
            - name: TINKOFF_API_SERVICE_URL
              value: http://lissa-trading-tinkoff-api-service:8082
