apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-auth-service
spec:
  selector:
    app: lissa-trading-auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP