server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_service_db

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: auth_service_db

security:
  jwt:
    secret: a7T8mQ2xL5rH9jK0pB3zW1yNxV6c4oFhJkSiZPlGsYb
    expiration: 86400000
    refreshExpiration: 86400000

logging:
  level:
    lissa.trading.auth.service.aspect: INFO
