apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-auth-service
  template:
    metadata:
      labels:
        app: lissa-trading-auth-service
    spec:
      containers:
        - name: auth-service
          image: kenpxrk1/lissa-trading-auth-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: lissa-trading-auth-service-config
            - secretRef:
                name: lissa-trading-auth-service-secret


