apiVersion: v1
kind: Secret
metadata:
  name: lissa-trading-auth-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cm9vdC1wYXNzd29yZC0xMjM=
  SECURITY_INTERNAL_TOKEN: WVhWMGFGTmxjblpwWTJVdGFXNTBaWEp1WVd3dGEyVjU=

