apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-auth-service
spec:
  selector:
    app: lissa-trading-auth-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
      nodePort: 30081
  type: NodePort
